services:
  app:
    image: delous/mdc-sensors
    restart: unless-stopped
    environment:
      API_URL: https://proka-bel.ru/api/v1/values
      DEVICE_ID: orangepi_prokabel
    volumes:
      - data:/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
  data:
